"""
MedConnect — Admin Configuration
==================================
Custom admin views for the User model with:
  • Auto-generated User ID display
  • Role-based filtering (all 6 roles)
  • Colored role badges
  • Organized fieldsets
  • OTP audit log
"""

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.utils.html import format_html

from .models import User, OTP


# ─────────────────────────────────────────────────────────────────────
#  ADMIN SITE CONFIGURATION
# ─────────────────────────────────────────────────────────────────────

admin.site.site_header = 'MedConnect Admin'
admin.site.site_title = 'MedConnect Admin Portal'
admin.site.index_title = 'MedConnect — Digital Healthcare Platform'


# ─────────────────────────────────────────────────────────────────────
#  OTP ADMIN
# ─────────────────────────────────────────────────────────────────────

@admin.register(OTP)
class OTPAdmin(admin.ModelAdmin):
    """Admin view for OTP records (read-only for auditing)."""

    list_display = [
        'short_id', 'phone', 'attempts', 'is_verified',
        'is_expired', 'expires_at', 'created_at',
    ]
    list_filter = ['is_verified', 'is_expired', 'created_at']
    search_fields = ['phone']
    readonly_fields = [
        'id', 'phone', 'otp_hash', 'attempts', 'is_verified',
        'is_expired', 'expires_at', 'created_at',
    ]
    ordering = ['-created_at']
    list_per_page = 25

    @admin.display(description='OTP ID')
    def short_id(self, obj):
        return str(obj.id)[:8] + '...'

    def has_add_permission(self, request):
        """OTPs are generated by the system, not manually."""
        return False

    def has_change_permission(self, request, obj=None):
        """OTPs should not be manually changed."""
        return False


# ─────────────────────────────────────────────────────────────────────
#  USER ADMIN
# ─────────────────────────────────────────────────────────────────────

@admin.register(User)
class UserAdmin(BaseUserAdmin):
    """
    Custom admin view for all MedConnect user roles.
    
    Shows auto-generated user_id, role badges, and organized fieldsets.
    Supports filtering by all 6 roles: 
    Patient, Doctor, Nurse, Pharmacist, Reception, Admin
    """

    # ── List Display ─────────────────────────────────────────────────
    list_display = [
        'user_id', 'full_name', 'phone', 'role_badge',
        'username', 'is_active_badge', 'is_phone_verified',
        'date_joined',
    ]

    list_display_links = ['user_id', 'full_name']

    list_filter = [
        'role', 'gender', 'is_active', 'is_phone_verified',
        'is_profile_complete', 'is_staff', 'date_joined',
    ]

    search_fields = [
        'user_id', 'phone', 'full_name', 'email',
        'username', 'city', 'emergency_contact_name',
    ]

    ordering = ['-date_joined']
    list_per_page = 25

    # ── Fieldsets ────────────────────────────────────────────────────
    fieldsets = (
        ('🆔 Identity & Authentication', {
            'fields': (
                'user_id', 'username', 'phone', 'email',
                'password', 'role',
            ),
        }),
        ('👤 Personal Information', {
            'fields': (
                'full_name', 'date_of_birth', 'gender',
                'blood_group', 'avatar',
            ),
        }),
        ('📍 Address', {
            'fields': (
                'address_line_1', 'address_line_2',
                'city', 'state', 'pincode',
            ),
            'classes': ('collapse',),
        }),
        ('🚨 Emergency Contact', {
            'fields': (
                'emergency_contact_name',
                'emergency_contact_phone',
                'emergency_contact_relation',
            ),
            'classes': ('collapse',),
        }),
        ('🏥 Medical Information', {
            'fields': ('known_allergies', 'existing_conditions'),
            'classes': ('collapse',),
        }),
        ('📋 Insurance', {
            'fields': ('insurance_provider', 'insurance_policy_number'),
            'classes': ('collapse',),
        }),
        ('✅ Status & Verification', {
            'fields': (
                'is_active', 'is_staff', 'is_superuser',
                'is_phone_verified', 'is_email_verified',
                'is_profile_complete',
            ),
        }),
        ('🔔 Push Notifications', {
            'fields': ('fcm_token',),
            'classes': ('collapse',),
        }),
        ('🕐 System Fields', {
            'fields': ('date_joined', 'updated_at', 'last_login'),
            'classes': ('collapse',),
        }),
        ('🔑 Permissions', {
            'fields': ('groups', 'user_permissions'),
            'classes': ('collapse',),
        }),
    )

    # ── Add User Fieldsets ───────────────────────────────────────────
    add_fieldsets = (
        ('Create New User', {
            'classes': ('wide',),
            'fields': (
                'phone', 'full_name', 'role', 'username',
                'password1', 'password2',
            ),
        }),
    )

    readonly_fields = ['user_id', 'date_joined', 'updated_at', 'last_login']

    # ── Custom Display Methods ───────────────────────────────────────

    @admin.display(description='Role', ordering='role')
    def role_badge(self, obj):
        """Display role as a colored badge."""
        colors = {
            'PATIENT':     '#3498db',   # Blue
            'DOCTOR':      '#27ae60',   # Green
            'NURSE':       '#f39c12',   # Orange
            'PHARMACIST':  '#9b59b6',   # Purple
            'RECEPTION':   '#1abc9c',   # Teal
            'ADMIN':       '#e74c3c',   # Red
        }
        color = colors.get(obj.role, '#95a5a6')
        return format_html(
            '<span style="background:{}; color:#fff; padding:3px 10px; '
            'border-radius:12px; font-size:11px; font-weight:600;">{}</span>',
            color,
            obj.get_role_display(),
        )

    @admin.display(description='Active', boolean=True, ordering='is_active')
    def is_active_badge(self, obj):
        return obj.is_active

    # ── Actions ──────────────────────────────────────────────────────
    actions = ['activate_users', 'deactivate_users']

    @admin.action(description='Activate selected users')
    def activate_users(self, request, queryset):
        count = queryset.update(is_active=True)
        self.message_user(request, f'{count} user(s) activated.')

    @admin.action(description='Deactivate selected users')
    def deactivate_users(self, request, queryset):
        count = queryset.update(is_active=False)
        self.message_user(request, f'{count} user(s) deactivated.')
