# Generated by Django 4.2.30 on 2026-06-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that issued this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_channel',
            field=models.CharField(choices=[('COUNTER', 'Counter'), ('ONLINE', 'Online')], default='COUNTER', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID.', max_length=255),
        ),
    ]
