# Generated by Django 5.2.13 on 2026-04-28 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('LAB', 'Lab Test'), ('IMAGING', 'Imaging'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other')], default='LAB', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded report file (PDF/image).', null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered')], db_index=True, default='ORDERED', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='appointments.appointment')),
                ('ordered_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'db_table': 'lab_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 diagnosis code (e.g., J06.9)', max_length=20)),
                ('condition_name', models.CharField(help_text='Diagnosis / Condition name', max_length=255)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='MILD', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date.', null=True)),
                ('is_chronic', models.BooleanField(default=False, help_text='Whether this is a chronic/ongoing condition.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnoses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='idx_diag_patient_date'), models.Index(fields=['icd_code'], name='idx_diag_icd')],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField(blank=True, help_text='Patient-reported primary complaint.')),
                ('history_of_present_illness', models.TextField(blank=True, help_text='HPI — detailed narrative of current illness.')),
                ('examination_findings', models.TextField(blank=True, help_text='Physical examination findings.')),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's overall clinical assessment.")),
                ('treatment_plan', models.TextField(blank=True, help_text='Prescribed treatment approach.')),
                ('advice', models.TextField(blank=True, help_text='General advice / lifestyle recommendations.')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='idx_medrec_patient_date')],
            },
        ),
    ]
