"""
Django settings for MedConnect — Digital Healthcare Platform.

Backend: Django + DRF + Djoser + SimpleJWT
Frontend: Flutter (mobile patient app) + Web dashboards
Database: SQLite (dev) → PostgreSQL (production)

Generated by 'django-admin startproject' using Django 4.2.6.
"""

import os
# from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR / ".env")
# ─────────────────────────────────────────────────────────────────────
#  SECURITY
# ─────────────────────────────────────────────────────────────────────
# print("DB PASSWORD:", os.environ.get("DB_PASSWORD"))
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# ─────────────────────────────────────────────────────────────────────
#  APPLICATION DEFINITION
# ─────────────────────────────────────────────────────────────────────

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'drf_spectacular',
    'phonenumber_field',
    'corsheaders',

    # MedConnect apps
    'accounts.apps.AccountsConfig',
    'healthcard.apps.HealthcardConfig',
    'appointments.apps.AppointmentsConfig',
    'prescriptions.apps.PrescriptionsConfig',
    'medical_records.apps.MedicalRecordsConfig',
    'billing.apps.BillingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medconnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medconnect.wsgi.application'


# ─────────────────────────────────────────────────────────────────────
#  DATABASE  (SQLite for dev, PostgreSQL for production)
# ─────────────────────────────────────────────────────────────────────

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "Life_Track_DB",
#         "USER": "postgres",
#         "PASSWORD": "Admin@1234",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}

# ─────────────────────────────────────────────────────────────────────
#  CUSTOM USER MODEL  (SDD Section 7.1)
# ─────────────────────────────────────────────────────────────────────

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.CustomAuthBackend',
]

# ─────────────────────────────────────────────────────────────────────
#  PASSWORD VALIDATION
# ─────────────────────────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─────────────────────────────────────────────────────────────────────
#  DJANGO REST FRAMEWORK
# ─────────────────────────────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'otp_send': '1/minute',
        'otp_send_hourly': '5/hour',
    },
    'EXCEPTION_HANDLER': 'accounts.utils.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%SZ',
}

# Add BrowsableAPI renderer in debug mode
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer'
    )


# ─────────────────────────────────────────────────────────────────────
#  JWT CONFIGURATION  (SDD Section 10.1)
# ─────────────────────────────────────────────────────────────────────

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),       # SDD: 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),      # SDD: 30 days
    'ROTATE_REFRESH_TOKENS': True,                     # SDD: Single-use rotation
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_uuid',

    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.CustomTokenObtainPairSerializer',
}


# ─────────────────────────────────────────────────────────────────────
#  DJOSER CONFIGURATION
# ─────────────────────────────────────────────────────────────────────

DJOSER = {
    'USER_ID_FIELD': 'id',
    'LOGIN_FIELD': 'username',
    'SEND_ACTIVATION_EMAIL': False,
    'SEND_CONFIRMATION_EMAIL': False,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': False,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': False,
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'LOGOUT_ON_PASSWORD_CHANGE': True,
    'HIDE_USERS': True,

    'SERIALIZERS': {
        'user_create': 'accounts.serializers.DjoserUserCreateSerializer',
        'user': 'accounts.serializers.DjoserUserSerializer',
        'current_user': 'accounts.serializers.DjoserCurrentUserSerializer',
        'set_password': 'accounts.serializers.DjoserSetPasswordSerializer',
    },

    'PERMISSIONS': {
        'user': ['rest_framework.permissions.IsAuthenticated'],
        'user_list': ['accounts.permissions.IsAdmin'],
        'user_create': ['rest_framework.permissions.AllowAny'],
        'user_delete': ['accounts.permissions.IsAdmin'],
        'set_password': ['rest_framework.permissions.IsAuthenticated'],
        'token_create': ['rest_framework.permissions.AllowAny'],
        'token_destroy': ['rest_framework.permissions.IsAuthenticated'],
    },
}


# ─────────────────────────────────────────────────────────────────────
#  DRF-SPECTACULAR (OpenAPI / Swagger)
# ─────────────────────────────────────────────────────────────────────

SPECTACULAR_SETTINGS = {
    'TITLE': 'MedConnect API',
    'DESCRIPTION': (
        'Digital Healthcare Platform — REST API.\n\n'
        '## Authentication\n'
        '- **Staff/Admin**: Username + Password via `/auth/jwt/create/`\n'
        '- **Patient**: Phone + OTP via `/auth/send-otp/` → `/auth/verify-otp/`\n\n'
        '## Roles\n'
        'PATIENT | DOCTOR | NURSE | PHARMACIST | RECEPTION | ADMIN'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
    },
}


# ─────────────────────────────────────────────────────────────────────
#  PHONE NUMBER FIELD
# ─────────────────────────────────────────────────────────────────────

PHONENUMBER_DEFAULT_REGION = 'IN'       # Default region: India
PHONENUMBER_DB_FORMAT = 'E164'          # Store in E.164 format: +919876543210


# ─────────────────────────────────────────────────────────────────────
#  OTP CONFIGURATION  (SDD Section 10.1)
# ─────────────────────────────────────────────────────────────────────

OTP_EXPIRY_MINUTES = 5                  # SDD: 5-minute expiry
OTP_MAX_ATTEMPTS = 3                    # SDD: Max 3 verification attempts
OTP_COOLDOWN_SECONDS = 60               # SDD: 1 per 60 seconds
OTP_HOURLY_LIMIT = 5                    # SDD: Max 5 per hour
OTP_LENGTH = 6                          # SDD: 6-digit numeric


# ─────────────────────────────────────────────────────────────────────
#  INTERNATIONALIZATION
# ─────────────────────────────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# ─────────────────────────────────────────────────────────────────────
#  STATIC & MEDIA FILES
# ─────────────────────────────────────────────────────────────────────

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ─────────────────────────────────────────────────────────────────────
#  DEFAULT PRIMARY KEY FIELD TYPE
# ─────────────────────────────────────────────────────────────────────

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─────────────────────────────────────────────────────────────────────
#  CORS SETTINGS  (Flutter frontend communication)
# ─────────────────────────────────────────────────────────────────────

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all in dev, restrict in production

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',       # Flutter web
    'http://localhost:8080',       # Flutter web alt
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8080',
]

CORS_ALLOW_CREDENTIALS = True


# ─────────────────────────────────────────────────────────────────────
#  LOGGING (Production-ready)
# ─────────────────────────────────────────────────────────────────────

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'medconnect.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'healthcard': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'appointments': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'prescriptions': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'medical_records': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'billing': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
