# Generated by Django 4.2.30 on 2026-06-02 06:43

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full legal name of the organization. E.g., "Sri Sai Clinic"', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. E.g., "sri-sai-clinic"', max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Short name for display. E.g., "SSC"', max_length=50)),
                ('registration_number', models.CharField(blank=True, help_text='Medical council / government registration number.', max_length=100)),
                ('setup_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('HOSPITAL', 'Hospital')], db_index=True, default='CLINIC', help_text='CLINIC: lightweight mode (no departments required). HOSPITAL: full-featured with departments, lab, IPD.', max_length=10)),
                ('enable_departments', models.BooleanField(default=False, help_text='Enable department-based routing. CLINIC=False (doctors work independently). HOSPITAL=True (doctors assigned to departments).')),
                ('enable_lab', models.BooleanField(default=False, help_text='Enable lab test ordering and result management.')),
                ('enable_pharmacy', models.BooleanField(default=True, help_text='Enable pharmacy module (medicine dispensing, stock management).')),
                ('enable_ipd', models.BooleanField(default=False, help_text='Enable In-Patient Department (IPD) module: ward management, bed allocation.')),
                ('enable_analytics', models.BooleanField(default=False, help_text='Enable analytics dashboard: revenue reports, patient trends, doctor performance.')),
                ('enable_multi_doctor', models.BooleanField(default=True, help_text='Allow multiple doctors. Set False for solo-practitioner clinics.')),
                ('enable_online_booking', models.BooleanField(default=True, help_text='Allow patients to book appointments online via patient app.')),
                ('enable_telemedicine', models.BooleanField(default=False, help_text='Enable telemedicine/video consultation module.')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary contact number.', max_length=128, region=None)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email.', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Organization website URL.')),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Pincode must be 5–10 digits.', regex='^\\d{5,10}$')])),
                ('country', models.CharField(default='India', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo image.', null=True, upload_to='org_logos/%Y/')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='Organization timezone for scheduling.', max_length=50)),
                ('currency', models.CharField(default='INR', help_text='Currency code for billing. E.g., INR, USD.', max_length=5)),
                ('default_consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Default consultation fee when doctor fee is not set.', max_digits=10)),
                ('max_daily_patients', models.PositiveIntegerField(default=100, help_text='Maximum patients per day (for capacity planning).')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial')], db_index=True, default='ACTIVE', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch. Deactivating blocks all access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='idx_org_slug'), models.Index(fields=['setup_type', 'is_active'], name='idx_org_type_active')],
            },
        ),
    ]
