# Generated by Django 4.2.6 on 2026-04-24 06:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Phone number the OTP was sent to.', max_length=128, region=None)),
                ('otp_hash', models.CharField(help_text='SHA-256 hashed OTP value. Never store plain-text OTP.', max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts (max 3).')),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True when OTP is successfully verified.')),
                ('is_expired', models.BooleanField(default=False, help_text='Set to True when OTP expires or is invalidated.')),
                ('expires_at', models.DateTimeField(help_text='OTP expiration timestamp (5 minutes from creation).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when OTP was generated.')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'is_expired'], name='idx_otp_phone_active')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='Auto-generated user ID. Format: MC-PAT-2026-00001', max_length=25, unique=True)),
                ('username', models.CharField(blank=True, help_text='Username for admin/staff dashboard login.', max_length=150, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Primary phone number for login & OTP verification. Format: +919876543210', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email address for notifications.', max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('RECEPTION', 'Reception'), ('ADMIN', 'Admin')], db_index=True, default='PATIENT', help_text='User role determines RBAC permissions. Ref: SDD Section 10.1 Permission Matrix.', max_length=20)),
                ('full_name', models.CharField(help_text='Full name of the user (First + Last).', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age calculation & patient records.', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Gender: MALE | FEMALE | OTHER.', max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group (displayed on Health Card).', max_length=5)),
                ('avatar', models.ImageField(blank=True, help_text='Profile photo. Stored in S3/media in production.', null=True, upload_to='avatars/%Y/%m/')),
                ('address_line_1', models.CharField(blank=True, help_text='Street address line 1.', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Street address line 2 (apartment, suite, etc.).', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City name.', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State / Province.', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='ZIP / Postal code.', max_length=10, validators=[django.core.validators.RegexValidator(message='Pincode must be between 5 to 10 digits.', regex='^\\d{5,10}$')])),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person.', max_length=255)),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Emergency contact phone number.', max_length=128, null=True, region=None)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Relationship with emergency contact (e.g., Spouse, Parent).', max_length=50)),
                ('known_allergies', models.TextField(blank=True, help_text='Comma-separated list of known allergies.')),
                ('existing_conditions', models.TextField(blank=True, help_text='Comma-separated list of pre-existing medical conditions.')),
                ('insurance_provider', models.CharField(blank=True, help_text='Name of insurance provider.', max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, help_text='Insurance policy number.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active. Deactivate instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether user can access the Django admin site.')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Set to True after successful OTP verification.')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Set to True after email verification.')),
                ('is_profile_complete', models.BooleanField(default=False, help_text='True when user has completed all required profile fields. Used in SDD API response: isProfileComplete.')),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications.', max_length=512)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of user registration.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp.')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['phone'], name='idx_user_phone'), models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['role'], name='idx_user_role'), models.Index(fields=['user_id'], name='idx_user_user_id'), models.Index(fields=['is_active', 'role'], name='idx_user_active_role')],
            },
        ),
    ]
