# Generated by Django 4.2.30 on 2026-06-03 05:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Uploaded ID proof file. Max size 5MB.', null=True, upload_to='id_proofs/%Y/%m/', validators=[accounts.models.validate_file_size]),
        ),
    ]
