# Generated by Django 5.2.13 on 2026-04-28 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream/Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('POWDER', 'Powder'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, help_text='E.g., 500mg, 250mg/5ml', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this level.')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'generic_name'], name='idx_med_name_generic'), models.Index(fields=['category'], name='idx_med_category')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AT_PHARMACY', 'At Pharmacy'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=25)),
                ('diagnosis_summary', models.TextField(blank=True, help_text='Brief diagnosis for pharmacy reference.')),
                ('notes', models.TextField(blank=True, help_text='Doctor notes / instructions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional — not every prescription comes from an appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['PHARMACIST', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_order', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Pharmacy Order',
                'verbose_name_plural': 'Pharmacy Orders',
                'db_table': 'pharmacy_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(help_text='E.g., 1 tablet, 5ml, 2 puffs', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BD', 'Twice Daily'), ('TDS', 'Thrice Daily'), ('QID', 'Four Times Daily'), ('SOS', 'As Needed'), ('STAT', 'Immediately'), ('HS', 'At Bedtime'), ('AC', 'Before Meals'), ('PC', 'After Meals')], default='OD', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Number of days.')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity to dispense.')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (take with food, etc.)')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'db_table': 'prescription_items',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='idx_rx_patient_status'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'created_at'], name='idx_rx_doctor_date'),
        ),
    ]
