# Generated by Django 4.2.30 on 2026-06-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization-specific medicine catalog entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization where this prescription was issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='organizations.organization'),
        ),
    ]
