# Generated by Django 5.2.13 on 2026-04-28 07:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee in INR.', max_digits=10)),
                ('bio', models.TextField(blank=True, help_text='Doctor bio for patient-facing profile.')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_available', models.BooleanField(default=True)),
                ('max_patients_per_slot', models.PositiveIntegerField(default=1, help_text='Max concurrent patients per time slot.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='appointments.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(db_index=True)),
                ('time_slot', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('BOOKED', 'Pre-Booked'), ('WALK_IN', 'Walk-In')], default='BOOKED', max_length=10)),
                ('token_number', models.CharField(blank=True, help_text='Queue token (e.g., T-042). Auto-generated.', max_length=10)),
                ('queue_position', models.PositiveIntegerField(default=0, help_text='Current position in doctor queue.')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CHECKED_IN', 'Checked In'), ('VITALS_DONE', 'Vitals Done'), ('WITH_DOCTOR', 'With Doctor'), ('CONSULTATION_DONE', 'Consultation Done'), ('AT_PHARMACY', 'At Pharmacy'), ('DISPENSED', 'Dispensed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='BOOKED', max_length=20)),
                ('priority', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='MILD', help_text='Triage priority. Higher priority = earlier in queue.', max_length=10)),
                ('chief_complaint', models.TextField(blank=True, help_text='Primary reason for visit.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from reception/nurse.')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='appointments.doctorprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'time_slot', 'queue_position'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_min', models.PositiveIntegerField(default=15, help_text='Duration of each slot in minutes.')),
                ('max_patients', models.PositiveIntegerField(default=20, help_text='Maximum patients for this schedule block.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'db_table': 'doctor_schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure_sys', models.PositiveIntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('blood_pressure_dia', models.PositiveIntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate / Pulse (bpm)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature (°F)', max_digits=4, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='Oxygen saturation (%)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Breaths per minute', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm)', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='BMI (auto-calculated)', max_digits=4, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose (mg/dL)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role__in': ['NURSE', 'DOCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
                'db_table': 'vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='idx_appt_patient_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='idx_appt_doctor_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='idx_appt_status_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['token_number'], name='idx_appt_token'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
