# Generated by Django 4.2.30 on 2026-06-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization where this appointment is booked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this department belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this doctor works for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profiles', to='organizations.organization'),
        ),
    ]
