# Generated by Django 5.2.13 on 2026-04-28 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='healthcards/qr/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('LOST', 'Lost / Reported'), ('REPLACED', 'Replaced')], default='ACTIVE', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Card',
                'verbose_name_plural': 'Health Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CONSULTATION', 'Consultation'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing'), ('GENERAL', 'General Lookup')], default='GENERAL', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_scans', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='healthcard.healthcard')),
            ],
            options={
                'verbose_name': 'Card Scan Log',
                'verbose_name_plural': 'Card Scan Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
