# Generated by Django 4.2.30 on 2026-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='is_elite',
            field=models.BooleanField(default=False, help_text='True if the patient purchased the Elite card.'),
        ),
    ]
